# -*- coding: utf-8 -*-
"""testCNN_eg1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c6gjgb-vYgdJntc6lghR9gI2bMLETZOj
"""

import numpy as np
import tensorflow as tf

from google.colab import drive
 
drive.mount("/content/gdrive/")

model_file = tf.keras.models.load_model('/content/gdrive/MyDrive/model file/model_face_recog_eg1.h5')

path = input('Enter the path of your image in order to predict:')
# path = '/content/gdrive/MyDrive/Dataset/test/Obama/BO120.jpg'

import matplotlib.pyplot as plt
img = tf.keras.preprocessing.image.load_img(path, target_size=(160,160))
plt.imshow(tf.keras.preprocessing.image.load_img(path))
dictionary = {0:'Daw Aung San SuuKyi',1:'Jackie Chan',2:'Messi',3:'Barack Obama'}
x = tf.keras.preprocessing.image.img_to_array(img)
x = np.expand_dims(x,axis=0)
x /= 255.0
images = np.vstack([x])
classes = model_file.predict(x)
y_classes=classes.argmax(axis=-1)
label = y_classes[0]#9
#print(label)
print("Model မှခန့်မှန်း လိုက်သော အဖြေမှာ ",dictionary[label], "ဖြစ်ပါသည်။")

